<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-QUKCJDR" ignored="0" name="Test" tests="3" failures="1" timestamp="24 Dec 2017 17:36:30 GMT" time="35.165" errors="0">
  <testcase name="start" time="35.001" classname="package1.Test1"/>
  <testcase name="navigate_to_main_window" time="0.098" classname="package1.Test1"/>
  <testcase name="failing_it" time="0.005" classname="package1.Test1">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]at package1.Test1.failing_it(Test1.java:31)... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- failing_it -->
</testsuite> <!-- Test -->
